### ISSUE TITLE
Fatal error: futex robust_list not initialized by pthreads (Unknown syscall 386)

### ISSUE THREAD

**Issue by sonroyaalmerol** [sonroyaalmerol/steamcmd-arm64#7]
This is an issue with QEMU running steamcmd which will affect all M-series Mac hosts running this base image. A function is currently being used by steamcmd after a recent update but is not implemented by QEMU yet. Will be waiting for QEMU updates to fix this.

Submitted issue: https://gitlab.com/qemu-project/qemu/-/issues/2424

**Comment by sonroyaalmerol** [comment]
Decided on abandoning and removing QEMU from this image because of this issue.

**Comment by antoniolago** [comment]
Hello @sonroyaalmerol, great work, thanks for this project,

I think even tho the package don't directly use QEMU this issue is still relevant and maybe should be "open" (even if just for tracking) as it also happens if we try to run steamcmd.sh inside Github Actions "ubuntu" runner with QEMU, the only (free) alternative to that being create a self-hosted ARM64 runner so it's doable without QEMU...

**Comment by sonroyaalmerol** [comment]
I'll be pinning the issue but will be staying closed. Based on the conversations with some contributors of QEMU (see the Gitlab issue), the fix for this issue is extremely difficult for them to implement (and impractical) so I'm not hopeful for this to be fixed at all seeing that they closed my issue as is.

Unfortunately, the only way I see this being resolved is if Valve updates steamcmd and somehow removes the problematic `set_robust_list` syscall which I doubt they will.

**Comment by Chocolate-Jeff** [comment]
I know this is 2 years late but I would put it into Valve's github repo for steam for linux(its also for steamCMD):
[here](https://github.com/ValveSoftware/steam-for-linux/issues)
