### ISSUE TITLE
Assertion failed: p_rcu_read->depth != 0

### ISSUE THREAD

**Issue by arobson** [sonroyaalmerol/steamcmd-arm64#8]
Hello,

when attempting to run the `steamcmd.sh `script in the home directory, I get:

```sh
/usr/local/bin/box86: error while loading shared libraries: libc.so.6: ELF load command address/offset not page-aligned
```

if I try instead to run the executable directly  (`linux32/steam`), I get this error instead:
```sh
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 102)
Aborted (core dumped)
```

Here is a rundown of my environment:

Raspberry Pi 5 (arm64/v8)
Linux 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64
Docker version 27.3.1, build ce12230

Any advice or guidance you can offer is appreciated. Thank you.

**Comment by sonroyaalmerol** [comment]
Hi, @arobson. I'm not sure if you've already figured it out but I would try and check to see if it's due to Raspberry Pi having a page size of 16k by default. I don't have an rpi5 myself but you can try using this as a guide: https://pimylifeup.com/raspberry-pi-page-size/

I've received issues before with box86 when the page size of the kernel is not 4k.

**Comment by sonroyaalmerol** [comment]
Closing this issue for now. Feel free to reopen if you're still having the same issue.
